package com.ipfdigital.bee.automation.test.mx.generator;

import com.ipfdigital.bee.automation.test.mx.engine.Field;

public enum DataField implements Field {
    MF_SCORE("MF_SCORE"),
    FREE_MONTHLY_INCOME("FREE_MONTHLY_INCOME"),
    PREV_WITHDRAWAL_AM("PREV_WITHDRAWAL_AM"),
    R_MIN_REALREPAYMENT_MMP_3M("R_MIN_REALREPAYMENT_MMP_3M"),
    INVOICES_PAID_MONTHLY_LATE_M_3("INVOICES_PAID_MONTHLY_LATE_M_3"),
    MAX_DAYS_BETWEEN_DRAWS_IN_PERIOD_V1("MAX_DAYS_BETWEEN_DRAWS_IN_PERIOD_V1"),
    OVERDUE_DAYS_SQUARED_12M("OVERDUE_DAYS_SQUARED_12M"),
    PREV_LATE_LAST_INVOICE_IN_PERIOD_V1("PREV_LATE_LAST_INVOICE_IN_PERIOD_V1"),
    TIME_SINCE_FIRST_CUST_IN_PERIOD_V2("TIME_SINCE_FIRST_CUST_IN_PERIOD_V2"),
    DAYS_SINCE_LAST_ACCOUNT_OPEN("DAYS_SINCE_LAST_ACCOUNT_OPEN"),
    INQUIRIES_IN_60_DAYS("INQUIRIES_IN_60_DAYS"),
    NUMBER_OF_REVOLVING_ACCOUNTS("NUMBER_OF_REVOLVING_ACCOUNTS"),
    OVERDUE_BALANCE("OVERDUE_BALANCE"),
    AMOUNT_OF_FIXED_AND_MORTGAGE_PAYMENT("AMOUNT_OF_FIXED_AND_MORTGAGE_PAYMENT"),
    RS_09_1("RS_09_1"),
    NET_INCOME("NET_INCOME"),
    EDUCATION("EDUCATION"),
    APPS_REGULAR_REJECTED_M_6("APPS_REGULAR_REJECTED_M_6"),
    DEPENDENTS_IN_HOUSEHOLD("DEPENDENTS_IN_HOUSEHOLD"),
    OPEN_PERSONAL_LOANS("OPEN_PERSONAL_LOANS"),
    OPEN_CREDIT_CARDS("OPEN_CREDIT_CARDS"),
    RS_04_1("RS_04_1"),
    RS_13_1("RS_13_1"),
    TOTAL_AMOUNT_OF_MAXIMUM_CREDITS("TOTAL_AMOUNT_OF_MAXIMUM_CREDITS"),
    YEARS_SINCE_MOST_RECENT_ACCOUNT("YEARS_SINCE_MOST_RECENT_ACCOUNT"),
    OPERATING_SYSTEM("OPERATING_SYSTEM"),
    DATE_OF_BIRTH("DATE_OF_BIRTH");

    private final String dataField;

    DataField(String dataField) {
        this.dataField = dataField;
    }

    @Override
    public String getContextKey() {
        return dataField;
    }
}
